//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClient.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class logpass
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public int ID { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual personalWorker personalWorker { get; set; }
        public virtual vacancy vacancy { get; set; }
    }
}
