//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClient.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class personalWorker
    {
        public string Login { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string DataOfBirthWorker { get; set; }
        public string ActivityWorker { get; set; }
        public string EducationWorker { get; set; }
        public string Company { get; set; }
    
        public virtual logpass logpass { get; set; }
    }
}
