//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClient.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacancy
    {
        public string Login { get; set; }
        public string position { get; set; }
        public string description { get; set; }
        public string salary { get; set; }
        public string city { get; set; }
        public string employment { get; set; }
        public string Login_Vidgyk { get; set; }
    
        public virtual logpass logpass { get; set; }
    }
}
